name: maven-test

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build
        run: |
          ls -ltr
          pwd
          chmod +x run.sh
          bash run.sh
      - name: Zip project artifact
        # run: |
        #   zip -r project.zip * -x '*.git*'
        uses: thedoctor0/zip-release@master
        with:
          filename: project.zip
          path: ./
          exclusions: '*.git*  *.github*'
      # - uses: shallwefootball/s3-upload-action@master
      #   with:
      #     S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      #     source_dir: 'project.zip'
      # - name: install aws
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install awscli -y    
      - name: Upload project artifact to s3 bucket
        env:
          AWS_REGION: ap-south-1
          #S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        
        run: |
           aws s3 cp project.zip  s3://dry-run009
        

      # - name: Deploy to S3
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV  }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      #   run: |
      #     aws s3 cp project.zip  s3://dry-run009